Er collab
NYPL/digarch pull request #26
Opened 2022-01-20 19:15 UTC by nkrabben

2022-01-20 19:51 UTC, arhonemus commented
![](https://github.trello.services/images/mini-trello-icon.png) [Review PR #26](https://trello.com/c/oXLn8aeV/45-review-pr-26)

2022-01-21 21:13 UTC, dreyjo commented on project-management/electronic-records-steps-collaboration.md
> +### Survey Directories (DRAFT)
How do we want to word drafts/processes that may change? Potentially a label?

2022-01-21 21:13 UTC, dreyjo commented on accessioning/inventorying-digital-media-accession.md
> +{: .label .label-red }
Is it possible for this label to be in line with the section 5 header or below it? Just so it's closer to what is being deprecated.

2022-01-21 21:13 UTC, dreyjo commented on accessioning/digitalmediaseparation.md
> +{: .label .label-red }
Is it possible for this label to be in line with the section 5 header or below it? Just so it's closer to what is being deprecated.

2022-01-21 21:43 UTC, arhonemus approved these changes

2022-01-24 15:03 UTC, arhonemus requested changes
Label changes

2022-01-24 15:06 UTC, arhonemus requested changes
label changes

2022-01-24 15:23 UTC, arhonemus requested changes
labels

2022-01-24 15:59 UTC, arhonemus requested changes
label

2022-01-24 16:31 UTC, arhonemus approved these changes
@dreyjo The label changes now appear in the pull request. (The previous comments I made failed to sync the changes.)

2022-02-01 14:53 UTC, nkrabben commented
Label solution looks good. I'm merging this.

2022-02-01 14:53 UTC, merged