Acq id bash
NYPL/digarch pull request #72
Opened 2023-11-17 15:57 UTC by nkrabben

Immediate changes made to all transfer pages that use bash scripts or commands.

Swapped in ACQ_acqID_specObjectID wherever it made sense and changed mentions of collection to acquisition.

I think the whole transfer section could use a good readthrough to find and replace collection with acquisition. Better to hold off on this while considering wholesale rewrites to multiple pages since we spend a lot of time repeating instructions between Mac and WSL and different transfer methods.

2023-11-20 21:12 UTC, arhonemus commented on transfers/file-transfers.md
> +```mkdir -p ACQ_acqID/ACQ_acqID_specObjectID{1..9}/{metadata,objects}```
```mkdir -p ACQ_acqID/ACQ_acqID_specObjectID/{metadata,objects}```
```suggestion
```mkdir -p ACQ_acqID/ACQ_acqID_specObjectID{1..9}/{metadata,objects}```  
```

2023-11-20 21:13 UTC, arhonemus commented on transfers/file-transfers.md
> +```mkdir -p ACQ_acqID/ACQ_acqID_specObjectID{1,5,7,9}/{metadata,objects}```
```suggestion
```mkdir -p ACQ_acqID/ACQ_acqID_specObjectID{10..99}/{metadata,objects}```  
```mkdir -p ACQ_acqID/ACQ_acqID_specObjectID{1,5,7,9}/{metadata,objects}```  
```

2023-11-20 21:17 UTC, arhonemus commented on transfers/file-transfers.md
> +```mkdir -p ACQ_acqID/ACQ_acqID_specObjectID{10..99}/{metadata,objects}```
```suggestion
```mkdir -p ACQ_acqID/ACQ_acqID_specObjectID/{metadata,objects}```  
```

2023-11-20 21:18 UTC, arhonemus commented on transfers/file-transfers.md
```suggestion
  
```

2023-11-20 21:22 UTC, arhonemus commented on transfers/file-transfers.md
```suggestion

```

2023-11-20 21:30 UTC, arhonemus requested changes
remove bracketed numbers in the mkdir command across pages.

2023-12-07 19:07 UTC, nkrabben commented
> remove bracketed numbers in the mkdir command across pages.

removed

2023-12-12 16:43 UTC, arhonemus approved these changes

2023-12-12 16:43 UTC, merged